import type { Property, Tenant, MaintenanceRequest, Payment } from '../types';

// Mock Properties Data
export const properties: Property[] = [
    {
        id: '1',
        _id: 'mock-prop-1',
        name: 'Sunset Apartments',
        address: '123 Main St, Downtown',
        type: 'apartment',
        units: 24,
        occupiedUnits: 22,
        monthlyRent: 28800,
        status: 'active',
        amenities: ['Parking', 'Gym', 'Pool', 'Laundry'],
        yearBuilt: 2018,
    },
    {
        id: '2',
        _id: 'mock-prop-2',
        name: 'Oak Street Condos',
        address: '456 Oak St, Midtown',
        type: 'condo',
        units: 12,
        occupiedUnits: 10,
        monthlyRent: 15000,
        status: 'active',
        amenities: ['Parking', 'Security', 'Elevator'],
        yearBuilt: 2020,
    },
    {
        id: '3',
        _id: 'mock-prop-3',
        name: 'Riverside House',
        address: '789 River Rd, Westside',
        type: 'house',
        units: 1,
        occupiedUnits: 1,
        monthlyRent: 2500,
        status: 'active',
        amenities: ['Garden', 'Garage', 'Fireplace'],
        yearBuilt: 2015,
    },
    {
        id: '4',
        _id: 'mock-prop-4',
        name: 'Downtown Plaza',
        address: '321 Commerce Blvd, Downtown',
        type: 'commercial',
        units: 8,
        occupiedUnits: 6,
        monthlyRent: 12000,
        status: 'maintenance',
        amenities: ['Parking', 'Security', '24/7 Access'],
        yearBuilt: 2010,
    },
];

// Mock Tenants Data
export const tenants: Tenant[] = [
    {
        id: '1',
        _id: 'mock-tenant-1',
        name: 'Sarah Wilson',
        email: 'sarah.w@email.com',
        phone: '(555) 123-4567',
        propertyId: '1',
        unitNumber: '4B',
        leaseStart: '2024-01-01',
        leaseEnd: '2025-12-31',
        monthlyRent: 1200,
        status: 'active',
        paymentStatus: 'paid',
        balance: 0,
        currentMonth: '2024-11',
    },
    {
        id: '2',
        _id: 'mock-tenant-2',
        name: 'Michael Chen',
        email: 'mchen@email.com',
        phone: '(555) 234-5678',
        propertyId: '1',
        unitNumber: '2A',
        leaseStart: '2024-03-01',
        leaseEnd: '2025-02-28',
        monthlyRent: 1500,
        status: 'active',
        paymentStatus: 'pending',
        balance: 1500,
        currentMonth: '2024-11',
    },
    {
        id: '3',
        _id: 'mock-tenant-3',
        name: 'Emily Rodriguez',
        email: 'emily.r@email.com',
        phone: '(555) 345-6789',
        propertyId: '2',
        unitNumber: '3C',
        leaseStart: '2024-02-15',
        leaseEnd: '2026-02-14',
        monthlyRent: 1800,
        status: 'active',
        paymentStatus: 'paid',
        balance: 0,
        currentMonth: '2024-11',
    },
];

// Mock Maintenance Requests
export const maintenanceRequests: MaintenanceRequest[] = [
    {
        id: '1',
        _id: 'mock-mr-1',
        propertyId: '1',
        unitNumber: '2A',
        tenantName: 'Michael Chen',
        title: 'Leaking Faucet',
        description: 'Kitchen faucet is dripping constantly',
        priority: 'medium',
        status: 'in-progress',
        createdAt: '2024-11-20T10:30:00Z',
        updatedAt: '2024-11-21T14:00:00Z',
    },
    {
        id: '2',
        _id: 'mock-mr-2',
        propertyId: '1',
        unitNumber: '4B',
        tenantName: 'Sarah Wilson',
        title: 'AC Not Working',
        description: 'Air conditioning unit not cooling properly',
        priority: 'high',
        status: 'pending',
        createdAt: '2024-11-24T09:15:00Z',
        updatedAt: '2024-11-24T09:15:00Z',
    },
    {
        id: '3',
        _id: 'mock-mr-3',
        propertyId: '2',
        unitNumber: '3C',
        tenantName: 'Emily Rodriguez',
        title: 'Light Fixture Replacement',
        description: 'Bedroom light fixture needs replacement',
        priority: 'low',
        status: 'completed',
        createdAt: '2024-11-15T16:45:00Z',
        updatedAt: '2024-11-18T11:30:00Z',
    },
];

// Mock Payments
export const payments: Payment[] = [
    {
        id: '1',
        _id: 'mock-pay-1',
        tenantId: '1',
        tenantName: 'Sarah Wilson',
        propertyName: 'Sunset Apartments - 4B',
        amount: 1200,
        date: '2024-11-01',
        status: 'completed',
        method: 'bank-transfer',
    },
    {
        id: '2',
        _id: 'mock-pay-2',
        tenantId: '3',
        tenantName: 'Emily Rodriguez',
        propertyName: 'Oak Street Condos - 3C',
        amount: 1800,
        date: '2024-11-01',
        status: 'completed',
        method: 'credit-card',
    },
    {
        id: '3',
        _id: 'mock-pay-3',
        tenantId: '2',
        tenantName: 'Michael Chen',
        propertyName: 'Sunset Apartments - 2A',
        amount: 1500,
        date: '2024-11-05',
        status: 'pending',
        method: 'bank-transfer',
    },
];
